Repository polkassembly/polkassembly, pull requests merged in 2023-05, with the labels that each got.

#37 Feat/open gov unlock
  pages/settings/index.tsx
  src/components/Balance/index.tsx
  src/components/Settings/DemocracyUnlock.tsx
  src/components/Settings/ReferendaUnlock.tsx
  src/components/Settings/Unlock.tsx
  src/moonbeamConvictionVoting.json
  src/ui-components/AccountSelectionForm.tsx
Labels: bug, enhancement, do not merge

#205 Feature/kr/overall sentiment
  public/assets/overall-sentiment/against.svg
  public/assets/overall-sentiment/for.svg
  public/assets/overall-sentiment/neutral.svg
  public/assets/overall-sentiment/pink-against.svg
  public/assets/overall-sentiment/pink-for.svg
  public/assets/overall-sentiment/pink-neutral.svg
  public/assets/overall-sentiment/pink-slightly-against.svg
  public/assets/overall-sentiment/pink-slightly-for.svg
  public/assets/overall-sentiment/slightly-against.svg
  public/assets/overall-sentiment/slightly-for.svg
  src/components/Post/Comment/CommentsContainer.tsx
  src/components/Post/Comment/EditableCommentContent.tsx
  src/types.ts
  src/ui-components/AddTags.tsx
  src/ui-components/Address.tsx
  src/ui-components/CreationLabel.tsx
  src/ui-components/UpdateLabel.tsx
Labels: in product testing

#218 fix: removing show more content feature from safari browser
  src/components/Post/Post.tsx
  src/components/Post/Tabs/PostDescription.tsx
Labels: bug

#209 discussion should come in openGov also
  src/components/AppLayout/GovernanceSwitchButton.tsx
  src/components/AppLayout/NavHeader.tsx
  src/components/AppLayout/index.tsx
  src/util/checkGov2Route.ts
Labels: in product testing, product-team-approved

#213 Fix/kr/edit username
  pages/api/v1/auth/actions/addProfile.ts
  pages/api/v1/auth/data/userProfileWithUsername.ts
  public/assets/icons/dashboard-profile.svg
  src/auth/auth.ts
  src/auth/types.ts
  src/auth/utils/messages.ts
  src/components/DelegationDashboard/index.tsx
  src/components/ImageComponent.tsx
  src/components/UserProfile/BasicInformation.tsx
  src/components/UserProfile/Details.tsx
  src/components/UserProfile/EditProfile.tsx
Labels: product-team-approved

#227 feat: commnents merged
  pages/api/v1/posts/off-chain-post.ts
  pages/api/v1/posts/on-chain-post.ts
  src/components/Post/Comment/CommentsContainer.tsx
Labels: enhancement

#226 Fix/open gov pagination
  pages/api/v1/listing/on-chain-posts-count.ts
  pages/auction-admin/index.tsx
  pages/big-spender/index.tsx
  pages/big-tipper/index.tsx
  pages/general-admin/index.tsx
  pages/lease-admin/index.tsx
  pages/medium-spender/index.tsx
  pages/member-referenda/index.tsx
  pages/referendum-canceller/index.tsx
  pages/referendum-killer/index.tsx
  pages/root/index.tsx
  pages/small-spender/index.tsx
  pages/small-tipper/index.tsx
  pages/staking-admin/index.tsx
  pages/treasurer/index.tsx
  pages/whitelisted-caller/index.tsx
  src/components/Listing/FellowshipReferendum/TrackListing.tsx
  src/components/Listing/FellowshipReferendum/TrackListingAllTabContent.tsx
  src/components/Listing/FellowshipReferendum/TrackListingCard.tsx
  src/components/Listing/FellowshipReferendum/TrackListingTabContent.tsx
  src/components/Listing/Tracks/TrackListingAllTabContent.tsx
  src/components/Listing/Tracks/TrackListingCard.tsx
  src/components/Listing/Tracks/TrackListingStatusTabContent.tsx
  src/queries.ts
Labels: product-team-approved

#245 Spam in comments
  pages/api/v1/auth/actions/reportContent.ts
  pages/api/v1/posts/off-chain-post.ts
  pages/api/v1/posts/on-chain-post.ts
  src/components/Post/Comment/Comment.tsx
  src/components/Post/Comment/EditableReplyContent.tsx
  src/components/Post/Comment/Replies.tsx
  src/components/Post/Comment/Reply.tsx
  src/ui-components/CreationLabel.tsx
Labels: in product testing

#228 fix enactment time
  src/components/BlockCountdown.tsx
  src/components/BlocksToTime.tsx
  src/components/Home/TreasuryOverview.tsx
  src/components/Post/GovernanceSideBar/index.tsx
  src/components/Post/Tabs/PostOnChainInfo/index.tsx
  src/util/__tests__/blockToTime.test.ts
  src/util/blockToTime.ts
Labels: in product testing
