Repository polkassembly/polkassembly, pull requests merged in 2023-10, with the labels that each got.

#755 Voted-modal-fixes
  src/components/Post/ActionsBar/ReportButton/index.tsx
  src/components/Post/Comment/Comment.tsx
  src/components/Post/Comment/Reply.tsx
  src/components/Post/PostHeading.tsx
  src/ui-components/CreationLabel.tsx
  styles/globals.css
Labels: dev-done

#787 Calender-events-in-descending-order
  src/components/Home/UpcomingEvents.tsx
Labels: dev-done

#791 Vote power fixes
  src/ui-components/CreationLabel.tsx
  styles/globals.css
Labels: dev-done

#811 Timeline-container-fixes
  src/components/Post/Tabs/PostTimeline/TimelineContainer.tsx
Labels: dev-done

#833 fix: :bug: propsal editing fix
  pages/api/v1/auth/actions/editPost.ts
Labels: do not merge, needs-investigation

#816 feat: See similar proposals
  analytics.ts
  pages/api/v1/listing/get-similar-posts.ts
  pages/api/v1/utils/similar-proposals.ts
  src/components/GovernanceCard.tsx
  src/components/Listing/Tracks/AboutTrackCard.tsx
  src/components/Listing/Tracks/TrackListingAllTabContent.tsx
  src/components/Post/Post.tsx
  src/components/Search/index.tsx
  src/components/Settings/ReferendaUnlock.tsx
  src/queries.ts
  src/util/messages.ts
  src/util/trackNameFromId.ts
Labels: dev-done, PR review

#840 See-similiar-proposal-ui-fixes
  src/components/GovernanceCard.tsx
  src/components/Listing/Tracks/TrackListingAllTabContent.tsx
  src/components/Post/Post.tsx
  src/ui-components/UIStates.tsx
Labels: dev-done
