Repository polkassembly/polkassembly, pull requests merged in 2023-09, with the labels that each got.

#598 Timer & Timeline Fixes
  src/components/Post/GovernanceSideBar/Referenda/ReferendaV2Messages.tsx
  src/components/Post/Tabs/PostTimeline/TimelineContainer.tsx
Labels: dev-done

#634 fix: kilt name state fix
  src/ui-components/Address.tsx
Labels: bug

#639 Button-UI-fixes
  public/assets/icons/delete.svg
  src/components/Post/ActionsBar/ReportButton/index.tsx
  src/components/Post/Comment/EditableReplyContent.tsx
Labels: dev-done

#527 Reason for Voting
  pages/api/v1/posts/on-chain-post.ts
  public/assets/icons/chatbox-icons/icon-left-quote.svg
  public/assets/icons/chatbox-icons/icon-right-quote.svg
  public/assets/icons/emoji-1.svg
  public/assets/icons/vector.svg
  src/components/ContentForm.tsx
  src/components/Post/Comment/Comment.tsx
  src/components/Post/Comment/CommentsContainer.tsx
  src/components/Post/GovernanceSideBar/Referenda/Modal/VoteSuccessModal.tsx
  src/components/Post/Post.tsx
  src/components/Post/PostCommentForm.tsx
  src/context/index.tsx
  src/types.ts
  src/ui-components/CommentSentimentModal.tsx
  src/ui-components/CreationLabel.tsx
  styles/globals.css
Labels: do not merge, dev-done

#653 SuccessModal-Info-UI-Fixes
  src/components/Balance/index.tsx
  src/components/Listing/Tracks/DelegateModal.tsx
  src/components/OpenGovTreasuryProposal/CreatePreimage.tsx
  src/components/OpenGovTreasuryProposal/CreateProposal.tsx
  src/components/OpenGovTreasuryProposal/DecisionDepositCard.tsx
  src/components/Post/GovernanceSideBar/PIPs/PIPsVote.tsx
  src/components/Post/GovernanceSideBar/Referenda/VoteReferendum.tsx
  src/components/Post/GovernanceSideBar/Referenda/VoteReferendumEth.tsx
  src/components/Post/GovernanceSideBar/Referenda/VoteReferendumEthV2.tsx
Labels: dev-done

#705 Fix-Open user profile on new tab
  src/components/Home/LatestActivity/columns.tsx
  src/components/UserProfile/EditProfile.tsx
  src/ui-components/Address.tsx
  src/ui-components/NameLabel.tsx
  src/ui-components/OnchainCreationLabel.tsx
  src/ui-components/TextEditor.tsx
Labels: in-dev

#707 Moonbean-calender-events-fixes
  src/components/Home/UpcomingEvents.tsx
Labels: dev-done

#712 User-description-alignment-fixes
  src/components/UserProfile/Details.tsx
Labels: dev-done

#710 Navbar-zindex-fixes
  src/components/AppLayout/NavHeader.tsx
  src/components/AppLayout/index.tsx
  styles/globals.css
Labels: dev-done
