Repository polkassembly/polkassembly, pull requests merged in 2023-07, with the labels that each got.

#328 fix: edit profile
  src/components/UserProfile/BasicInformation.tsx
  src/components/UserProfile/EditProfile.tsx
  src/components/UserProfile/Socials.tsx
  src/ui-components/SocialLinks.tsx
Labels: in product testing

#369 logos-on-username
  public/assets/icons/account-box-icon.svg
  public/assets/icons/mail-icon.svg
  public/assets/icons/screen-share-icon.svg
  public/assets/icons/twitter-icon.svg
  src/ui-components/IdentityBadge.tsx
Labels: changes-requested

#377 feat: new text editor
  package.json
  src/components/ContentForm.tsx
  src/components/Post/PostCommentForm.tsx
  src/ui-components/Markdown.tsx
  src/ui-components/TextEditor.tsx
  styles/globals.css
  yarn.lock
Labels: in product testing

#408 Fix/kr/username redirection
  src/ui-components/MarkdownEditor.tsx
Labels: changes-requested

#387 username check if it's under email or any link
  src/ui-components/MarkdownEditor.tsx
Labels: do not merge, changes-requested

#386 feat: post summary
  pages/api/v1/posts/off-chain-post.ts
  pages/api/v1/posts/on-chain-post.ts
  public/assets/icons/ai-star.svg
  public/assets/icons/openai.svg
  public/assets/icons/summary-modal-close.svg
  src/auth/utils/messages.ts
  src/components/Post/Post.tsx
  src/components/Post/PostHeading.tsx
  src/components/Post/PostSummary/index.tsx
  src/context/PostDataContext.tsx
  src/ui-components/CreationLabel.tsx
  src/ui-components/CustomIcons.tsx
  src/util/getPostContentAiSummary.ts
Labels: do not merge

#414 fix: mention auto generated username issue
  pages/address/[address].tsx
  pages/api/v1/auth/data/userProfileWithUsername.ts
  pages/api/v1/posts/on-chain-post.ts
  src/auth/utils/manualUsername25Char.ts
  src/auth/utils/messages.ts
  src/components/Post/Comment/Comment.tsx
  src/components/Post/Comment/EditableCommentContent.tsx
  src/components/Post/Comment/EditableReplyContent.tsx
  src/components/Post/Comment/Reply.tsx
  src/ui-components/Address.tsx
Labels: bug

#394 feat: hover on username
  public/assets/icons/email-icon.svg
  public/assets/icons/judgement-icon.svg
  public/assets/icons/legal-icon.svg
  public/assets/icons/pgp-icon.svg
  public/assets/icons/riot-icon.svg
  public/assets/icons/screen-share-icon.svg
  public/assets/icons/twitter-icon.svg
  public/assets/icons/web-icon.svg
  src/ui-components/IdentityBadge.tsx
Labels: in product testing

#421 Fix/kr/open gov
  pages/login/index.tsx
  src/components/AppLayout/GovernanceSwitchButton.tsx
  src/components/AppLayout/NavHeader.tsx
  src/components/AppLayout/index.tsx
  src/components/Search/SearchErrorsCard.tsx
  src/context/UserDetailsContext.tsx
  src/types.ts
  src/util/getCurrGovType.ts
Labels: changes-requested

#431 fix: decoding onChain info if binary character more than 10%
  pages/api/v1/posts/on-chain-post.ts
  src/components/Post/Tabs/PostOnChainInfo/ArgumentsTableJSONView/index.tsx
  src/util/decodingOnChainInfo.ts
Labels: bug

#448 fix: truncate text
  src/ui-components/IdentityBadge.tsx
Labels: in product testing

#396 Gov sidebar + cmnt timeline position fix
  src/components/Post/Comment/Comment.tsx
  src/components/Post/Comment/CommentsContainer.tsx
  src/components/Post/Comment/Reply.tsx
  src/components/Post/Post.tsx
  src/ui-components/CreationLabel.tsx
  src/ui-components/UserAvatar.tsx
Labels: in product testing

#402 feat: design hot fixes
  public/assets/icons/delegation-listing.svg
  src/components/Gov2Home/Gov2LatestActivity/AllGov2PostsTable.tsx
  src/components/Gov2Home/Gov2LatestActivity/TrackPostsTable.tsx
  src/components/Gov2Home/Gov2LatestActivity/index.tsx
  src/components/GovernanceCard.tsx
  src/components/Home/LatestActivity/PostsTable.tsx
  src/components/Home/LatestActivity/index.tsx
  src/components/Home/TreasuryOverview.tsx
  src/components/Listing/OffChain/OffChainCard.tsx
  src/components/Listing/Tracks/AboutTrackCard.tsx
  src/components/Listing/Tracks/DelegateModal.tsx
  src/components/Listing/Tracks/TrackListingAllTabContent.tsx
  src/components/Listing/Tracks/TrackListingCard.tsx
  src/components/Listing/Tracks/TrackListingStatusTabContent.tsx
  src/ui-components/FilterByTags.tsx
  src/ui-components/LatestActivityStates.tsx
  src/ui-components/TopicTag.tsx
Labels: in product testing
