Repository polkassembly/polkassembly, pull requests merged in 2023-08, with the labels that each got.

#385 Add polkasafe api for multisig
  next.config.js
  package.json
  pages/api/v1/auth/actions/addressLogin.ts
  pages/api/v1/auth/actions/addressSignupConfirm.ts
  pages/api/v1/auth/actions/addressSignupStart.ts
  pages/api/v1/getOnChainAddressData/index.ts
  pages/login/index.tsx
  pages/signup/index.tsx
  public/assets/multi-vote-initiated.svg
  public/assets/polkasafe-logo.svg
  src/auth/auth.ts
  src/auth/types.ts
  src/components/DelegationDashboard/DashboardTrack.tsx
  src/components/DelegationDashboard/DelegationWalletConnectModal.tsx
  src/components/DelegationDashboard/ProfileBalance.tsx
  src/components/DelegationDashboard/utils/checkIsAddressMultisig.ts
  src/components/Listing/Tracks/DelegateModal.tsx
  src/components/Listing/Tracks/DelegationSuccessPopup.tsx
  src/components/Listing/Tracks/UndelegateModal.tsx
  src/components/Login/MetamaskLogin.tsx
  src/components/Login/WalletButtons.tsx
  src/components/Login/Web2Login.tsx
  src/components/Login/Web3Login.tsx
  src/components/Post/GovernanceSideBar/Referenda/Modal/VoteSuccessModal.tsx
  src/components/Post/GovernanceSideBar/Referenda/VoteReferendum.tsx
  src/components/Signup/Web2Signup.tsx
  src/components/Signup/Web3Signup.tsx
  src/components/WalletButton/index.tsx
  src/context/UserDetailsContext.tsx
  src/global/networkConstants.ts
  src/hooks/usePolkasafe.ts
  src/types.ts
  src/ui-components/AccountSelectionForm.tsx
  src/ui-components/AddressDropdown.tsx
  src/ui-components/MultisigAccountSelectionForm.tsx
  src/util/canUsePolkasafe.ts
  yarn.lock
Labels: in product testing

#495 fix: can edit comment and reply, when comments are visible in another post
  pages/api/v1/posts/off-chain-post.ts
  pages/api/v1/posts/on-chain-post.ts
  src/components/Post/Comment/Comment.tsx
  src/components/Post/Comment/EditableCommentContent.tsx
  src/components/Post/Comment/EditableReplyContent.tsx
  src/components/Signup/Web2Signup.tsx
Labels: bug

#499 update showpolkasafe
  src/components/Login/Web2Login.tsx
  src/components/Signup/Web2Signup.tsx
Labels: bug

#500 hot fixed
  src/components/DelegationDashboard/DelegationWalletConnectModal.tsx
  src/components/Post/GovernanceSideBar/Referenda/VoteReferendum.tsx
  src/ui-components/MultisigAccountSelectionForm.tsx
Labels: bug

#490 Feature/kr/listing
  pages/api/v1/listing/on-chain-posts.ts
  src/components/DelegationDashboard/ActiveProposalCard.tsx
  src/components/DelegationDashboard/DelegateCard.tsx
  src/components/DelegationDashboard/ProfileBalance.tsx
  src/components/GovernanceCard.tsx
  src/components/Listing/FellowshipReferendum/TrackListingAllTabContent.tsx
  src/components/Listing/FellowshipReferendum/TrackListingTabContent.tsx
  src/components/Listing/Tracks/AboutTrackCard.tsx
  src/components/Listing/Tracks/DelegateModal.tsx
  src/components/Listing/Tracks/DelegationSuccessPopup.tsx
  src/components/Listing/Tracks/TrackListingAllTabContent.tsx
  src/components/Listing/Tracks/TrackListingStatusTabContent.tsx
  src/components/Listing/Tracks/UndelegateModal.tsx
  src/components/Listing/index.tsx
  src/components/Post/GovernanceSideBar/Referenda/Modal/VoteSuccessModal.tsx
  src/components/Post/GovernanceSideBar/Referenda/ReferendaV2Messages.tsx
  src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  src/components/Post/GovernanceSideBar/index.tsx
  src/queries.ts
  src/types.ts
  src/ui-components/BalanceInput.tsx
  src/ui-components/VotesProgressInListing.tsx
  src/util/formatedBalance.ts
  src/util/getPeriodData.ts
  src/util/getQueryToTrack.ts
  src/util/getReferendumVotes.ts
  src/util/getStatusBlock.ts
Labels: design-team-approved

#510 fix: ux improvements
  pages/api/v1/votes/index.ts
  src/components/Post/GovernanceSideBar/Referenda/VoteReferendum.tsx
  src/components/Post/GovernanceSideBar/Referenda/VotersList.tsx
  src/global/sortOptions.ts
Labels: in product testing

#457 feat: error boundary component for handling fallback ui, if app crash
  pages/_app.tsx
  src/ui-components/ErrorBoundary/Fallback.tsx
  src/ui-components/ErrorBoundary/index.tsx
Labels: enhancement, do not merge

#453 feat: changes for deploying moonbeam opengov
  src/components/AppLayout/OpenGovHeaderBanner.tsx
  src/components/AppLayout/index.tsx
  src/components/Settings/Unlock.tsx
  src/global/openGovNetworks.ts
  src/global/post_trackInfo.ts
Labels: enhancement

#483 feat: threshold listing view
  src/components/Listing/Tracks/AboutTrackCard.tsx
  src/components/Listing/Tracks/Curves.tsx
  src/components/Post/GovernanceSideBar/Referenda/util.ts
  src/components/Post/GovernanceSideBar/index.tsx
Labels: in product testing

#405 Comments infinity loading
  package.json
  pages/api/v1/posts/comments/getCommentByPostId.ts
  pages/api/v1/posts/comments/getCommentsWithId.ts
  pages/api/v1/posts/comments/getInitialComments.ts
  pages/api/v1/posts/comments/getOnlySubsquareComments.ts
  pages/api/v1/posts/comments/updateComments.ts
  pages/api/v1/posts/off-chain-post.ts
  pages/api/v1/posts/on-chain-post.ts
  pages/bounty/[id].tsx
  pages/child_bounty/[id].tsx
  pages/member-referenda/[id].tsx
  pages/motion/[id].tsx
  pages/post/[id].tsx
  pages/proposal/[id].tsx
  pages/referenda/[id].tsx
  pages/referendum/[id].tsx
  public/assets/icons/keyboard-double-arrow-up.svg
  src/components/Post/ActionsBar/ReportButton/index.tsx
  src/components/Post/Comment/Comment.tsx
  src/components/Post/Comment/Comments.tsx
  src/components/Post/Comment/CommentsContainer.tsx
  src/components/Post/Comment/EditableCommentContent.tsx
  src/components/Post/Comment/EditableReplyContent.tsx
  src/components/Post/Comment/utils/getPaginatedComments.ts
  src/components/Post/Comment/utils/getPostCommentsWithId.ts
  src/components/Post/Post.tsx
  src/components/Post/PostCommentForm.tsx
  src/context/PostDataContext.tsx
  src/ui-components/Address.tsx
  src/ui-components/CreationLabel.tsx
  src/ui-components/NameLabel.tsx
  src/ui-components/ScrollToTop.tsx
  src/ui-components/UserAvatar.tsx
  src/util/messages.ts
  yarn.lock
Labels: do not merge, in product testing

#568 feat!: add comment sentimental filter by backend
  pages/api/v1/posts/comments/getCommentByPostId.ts
  pages/api/v1/posts/comments/getInitialComments.ts
  pages/api/v1/posts/off-chain-post.ts
  pages/api/v1/posts/on-chain-post.ts
  src/components/Post/Comment/CommentsContainer.tsx
  src/components/Post/Comment/EditableCommentContent.tsx
  src/components/Post/Comment/EditableReplyContent.tsx
  src/components/Post/Comment/utils/getPaginatedComments.ts
  src/components/Post/Post.tsx
  src/context/CommentDataContext.tsx
  src/context/index.tsx
  src/util/messages.ts
Labels: breaking-change

#579 fix: non-substrate page's address fix
  pages/address/[address].tsx
Labels: dev-done

#582 fix: Governance Sicebar Scroll Issue Fixes
  src/components/Post/Post.tsx
  src/util/Stickytop.tsx
Labels: in-dev

#565 fix: Timeline UI Changes
  public/assets/icons/Democracy-Referenda-grey.svg
  public/assets/icons/Democracy-Referenda.svg
  public/assets/icons/discussion-icon-selected.svg
  public/assets/icons/discussion-icon-unselected.svg
  public/assets/icons/down-icon.svg
  public/assets/icons/learn-more-icon.svg
  public/assets/icons/motions-icon-selected.svg
  public/assets/icons/motions-icon-unselected.svg
  public/assets/icons/treasury-proposals-icon-grey.svg
  public/assets/icons/treasury-proposals-icon.svg
  public/assets/icons/up-arrow.svg
  public/assets/sidebar/democracy-proposal-icon-selected.svg
  public/assets/sidebar/democracy-proposal-icon-unselected.svg
  public/assets/sidebar/tech-comm-proposals-icon-selected.svg
  public/assets/sidebar/tech-comm-proposals-icon-unselected.svg
  public/assets/sidebar/treasury-child-bounties-icon-selected.svg
  public/assets/sidebar/treasury-child-bounties-icon-unselected.svg
  src/components/Post/Tabs/PostTimeline/TimelineContainer.tsx
  src/components/Post/Tabs/PostTimeline/index.tsx
Labels: dev-done
