Repository polkassembly/polkassembly, pull requests merged in 2023-06, with the labels that each got.

#267 feat/cere vote info
  src/components/Post/GovernanceSideBar/Referenda/ReferendumVoteInfo.tsx
  src/components/Post/GovernanceSideBar/index.tsx
  src/queries.ts
  src/ui-components/PassingInfoTag.tsx
Labels: bug, duplicate, enhancement

#273 Vote success state
  public/assets/icons/abstainGray.svg
  public/assets/icons/ayeGray.svg
  public/assets/icons/nayGray.svg
  public/assets/icons/split-yellow-icon.svg
  public/assets/icons/splitGray.svg
  src/components/Listing/Tracks/DelegationSuccessPopup.tsx
  src/components/Post/GovernanceSideBar/Referenda/VoteReferendum.tsx
  src/components/Post/GovernanceSideBar/Referenda/VoteReferendumEth.tsx
  src/components/Post/GovernanceSideBar/Referenda/VoteReferendumEthV2.tsx
  src/ui-components/Address.tsx
Labels: in product testing, product-team-approved

#274 added loader in voting info card
  src/components/Post/GovernanceSideBar/Referenda/ReferendumV2VoteInfo.tsx
Labels: in product testing, product-team-approved

#248 Enable to login with email
  src/auth/auth.ts
  src/auth/utils/messages.ts
  src/components/Login/Web2Login.tsx
  src/util/validation.ts
Labels: do not merge

#270 Audit UI for polkadot and kusama
  next.config.js
  package.json
  public/assets/icons/caution.svg
  public/assets/icons/pdfs.svg
  public/assets/icons/video.svg
  public/assets/no-audits.svg
  public/assets/wired-outline-334-loader-5.gif
  public/assets/wired-outline-334-loader-5.gif:Zone.Identifier
  src/components/Post/Post.tsx
  src/components/Post/Tabs/PostTimeline/Audit/ImageViewer.tsx
  src/components/Post/Tabs/PostTimeline/Audit/NoAuditReport.tsx
  src/components/Post/Tabs/PostTimeline/Audit/PdfViewer.tsx
  src/components/Post/Tabs/PostTimeline/Audit/VideoViewer.tsx
  src/components/Post/Tabs/PostTimeline/Audit/index.tsx
  styles/globals.css
  yarn.lock
Labels: in product testing

#299 fix: multiple reply buttons
  src/components/Home/TreasuryOverview.tsx
  src/components/Post/Comment/EditableReplyContent.tsx
Labels: bug

#300 bounties-list
  pages/api/v1/child_bounties/index.ts
  src/components/Post/GovernanceSideBar/Bounty/BountyChildBounties.tsx
  src/components/Post/GovernanceSideBar/index.tsx
  src/queries.ts
Labels: enhancement

#287 back-button
  pages/login/index.tsx
  pages/signup/index.tsx
  public/assets/icons/login-logo.svg
  src/components/Login/Web2Login.tsx
  src/components/Login/Web3Login.tsx
  src/components/Signup/Web2Signup.tsx
  src/components/Signup/Web3Signup.tsx
Labels: in product testing

#293 Usernames
  pages/api/v1/auth/actions/addProfile.ts
  pages/api/v1/auth/data/profileWithAddress.ts
  src/auth/auth.ts
  src/auth/types.ts
  src/components/Gov2Home/Gov2LatestActivity/AllGov2PostsTable.tsx
  src/components/GovernanceCard.tsx
  src/components/Post/Comment/Comment.tsx
  src/components/UserProfile/EditProfile.tsx
  src/ui-components/Address.tsx
  src/ui-components/CreationLabel.tsx
  src/ui-components/LatestActivityStates.tsx
  src/ui-components/NameLabel.tsx
  src/ui-components/OnchainCreationLabel.tsx
Labels: in product testing

#366 fix: onChainPost can now be linked to any discussion post but the discussion should not have a link with any other onChainPost
  pages/api/v1/auth/actions/linkPostConfirm.ts
  pages/api/v1/auth/actions/linkPostStart.ts
  src/components/Post/GovernanceSideBar/PostEditOrLinkCTA/LinkingAndEditing.tsx
Labels: bug, enhancement
