Repository polkassembly/polkassembly, pull requests merged in 2024-01, with the labels that each got.

#1145 fix: customButton fixes
  pages/calendar/index.tsx
  src/basic-components/buttons/CustomButton.tsx
  src/components/Calendar/CustomToolbar.tsx
  src/components/DelegationDashboard/Delegate.tsx
  src/components/GovernanceCard.tsx
  src/components/OpenGovTreasuryProposal/DecisionDepositCard.tsx
  src/components/Post/ActionsBar/ShareButton.tsx
  src/components/Post/ActionsBar/SubscriptionButton/SubscriptionButton.tsx
  src/components/Post/ActionsBar/TrackerButton.tsx
  src/components/Post/GovernanceSideBar/Motions/VoteMotion.tsx
  src/components/Post/Tabs/PostDescription.tsx
  src/components/PreImagesTable.tsx
  src/components/Settings/Delete.tsx
  src/ui-components/AyeNayButtons.tsx
  src/ui-components/CommentSentimentModal.tsx
  src/ui-components/QuickView.tsx
  src/ui-components/TextEditor.tsx
  src/ui-components/UIStates.tsx
Labels: in product testing, dev-done

#1081 Feature/post prediction card
  public/assets/icons/avatars/avatar-eth.png
  public/assets/icons/avatars/avatar-polkadot.png
  src/components/Post/GovernanceSideBar/index.tsx
  src/ui-components/PredictionCard/index.tsx
Labels: do not merge

#1152 feat: Loading designSystem Implementation
  pages/alliance/announcement/[id].tsx
  pages/alliance/motion/[id].tsx
  pages/bounty/[id].tsx
  pages/child_bounty/[id].tsx
  pages/community/[id].tsx
  pages/grant/[id].tsx
  pages/member-referenda/[id].tsx
  pages/motion/[id].tsx
  pages/post/[id].tsx
  pages/proposal/[id].tsx
  pages/referenda/[id].tsx
  pages/referendum/[id].tsx
  pages/tech/[id].tsx
  pages/technical/[id].tsx
  pages/tip/[hash].tsx
  pages/treasury/[id].tsx
  pages/upgrade/[id].tsx
  src/basic-components/Loading/LoadingState.tsx
  src/components/CouncilBoard/DiscussionsBoard/DiscussionPostClient.tsx
  src/components/CouncilBoard/ReferendaBoard/ReferendumPostClient.tsx
  src/components/Listing/FellowshipReferendum/TrackListingAllTabContent.tsx
  src/components/Listing/FellowshipReferendum/TrackListingTabContent.tsx
  src/components/Listing/Members/AllianceMembers.tsx
  src/components/Listing/Members/AllianceUnscrupulous.tsx
  src/components/Listing/Members/MembersContainer.tsx
  src/components/Listing/Tracks/TrackListingAllTabContent.tsx
  src/components/Listing/Tracks/TrackListingStatusTabContent.tsx
  src/components/Listing/WhitelistMembers/WhitelistMembersContainer.tsx
  src/components/Post/Post.tsx
  src/components/PreImagesTable.tsx
  src/components/Tracker/ListingContainer.tsx
  src/ui-components/LatestActivityStates.tsx
Labels: in product testing, dev-done

#1169 fix: buttonSize attribute fixes
  src/basic-components/buttons/CustomButton.tsx
  src/components/Calendar/CreateEventSidebar.tsx
  src/components/Calendar/CustomToolbar.tsx
  src/components/Listing/Tracks/DelegateModal.tsx
  src/components/Listing/Tracks/DelegateModalEthV2.tsx
  src/components/Listing/Tracks/UndelegateModal.tsx
  src/components/Login/MetamaskLogin.tsx
  src/components/Login/WalletConnectLogin.tsx
  src/components/Login/Web2Login.tsx
  src/components/Login/Web3Login.tsx
  src/components/OnchainIdentity/IdentityForm.tsx
  src/components/OnchainIdentity/SocialVerification.tsx
  src/components/OpenGovTreasuryProposal/DecisionDepositCard.tsx
  src/components/OpenGovTreasuryProposal/index.tsx
  src/components/Post/ActionsBar/OptionPoll/CreateOptionPoll.tsx
  src/components/Post/ActionsBar/ReportButton/index.tsx
  src/components/Post/GovernanceSideBar/PIPs/PIPsVote.tsx
  src/components/Post/GovernanceSideBar/Referenda/ReferendumV2VoteInfo.tsx
  src/components/Post/GovernanceSideBar/Referenda/VotingFrom.tsx
  src/components/Post/PostContentForm/LinkPostModal.tsx
  src/components/Post/PostContentForm/index.tsx
  src/components/Settings/DemocracyUnlock.tsx
  src/components/Settings/Notifications/NotificationChannels/Modals/ResetConfirmation.tsx
  src/components/Settings/ReferendaUnlock.tsx
  src/components/Settings/UserAccount/Modals/ChangeEmail.tsx
  src/components/Settings/UserAccount/Modals/ChangePassword.tsx
  src/components/Settings/UserAccount/Modals/ChangeUsername.tsx
  src/components/Settings/setOnChainIdentityButton.tsx
  src/components/Signup/MetamaskSignup.tsx
  src/components/Signup/WalletConnectSignup.tsx
  src/components/Signup/Web2Signup.tsx
  src/components/Signup/Web3Signup.tsx
  src/components/Tipping/index.tsx
  src/components/UserProfile/EditProfile.tsx
  src/ui-components/LoginSuccessModal.tsx
Labels: dev-done

#1173 fix: Pagination UI Fixes
  pages/alliance/announcements/index.tsx
  pages/alliance/motions/index.tsx
  pages/community/index.tsx
  pages/motions/index.tsx
  pages/preimages/index.tsx
  pages/tech-comm-proposals/index.tsx
  pages/technical/index.tsx
  pages/upgrade/index.tsx
  src/components/DelegationDashboard/ActiveProposals.tsx
  src/components/Listing/FellowshipReferendum/TrackListingCard.tsx
  src/components/Post/GovernanceSideBar/Modal/VoteData/DelegateVoteList.tsx
  src/components/Post/GovernanceSideBar/Referenda/VotersList.tsx
  src/components/Profile/CouncilVotes.tsx
  src/components/Search/ResultPeople.tsx
  src/components/Search/ResultPosts.tsx
  src/ui-components/Gif.tsx
Labels: product-team-approved, dev-done

#1168 feat: RPC Endpoints for different Chains
  src/components/AppLayout/NavHeader.tsx
  src/global/networkConstants.ts
Labels: dev-done, PR review, DEV Test Req

#1167 feat: slack notification on Polkassembly
  public/assets/icons/content-copy-pink.svg
  src/components/Settings/Notifications/NotificationChannels/BotSetupCard.tsx
  src/components/Settings/Notifications/NotificationChannels/Modals/Discord.tsx
  src/components/Settings/Notifications/NotificationChannels/Modals/Slack.tsx
  src/components/Settings/Notifications/NotificationChannels/Modals/Telegram.tsx
  src/components/Settings/Notifications/NotificationChannels/index.tsx
Labels: dev-done, PR review

#1196 Delegation-modal-fixes
  src/components/Listing/Tracks/DelegateModal.tsx
Labels: dev-done

#1162 Verfied-nudge-on-profile-page
  public/assets/icons/greyCalendar.svg
  public/assets/icons/shield-user-icon-pink.svg
  src/components/UserProfile/Details.tsx
  src/components/UserProfile/VerifiedInfo.tsx
  src/ui-components/Address.tsx
  styles/globals.css
Labels: dev-done, PR review

#1224 feat: Enable slack notification
  src/components/Settings/Notifications/NotificationChannels/index.tsx
Labels: dev-done

#1200 Status-filter-count
  src/components/Listing/Tracks/TrackListingAllTabContent.tsx
  src/components/Listing/Tracks/TrackListingCard.tsx
  src/components/Listing/Tracks/TrackListingStatusTabContent.tsx
  src/ui-components/filteredTags.tsx
Labels: in product testing, dev-done
